-- -----------------------------------------------------
-- Schema bus_depot_№1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS bus_depot_1 AUTHORIZATION postgres;

SET search_path TO bus_depot_1, public;

-- -----------------------------------------------------
-- Table `shift_route_round` - связующая таблица-справочник
-- -----------------------------------------------------
DROP TABLE IF EXISTS shift_route_round CASCADE;

CREATE TABLE IF NOT EXISTS shift_route_round (
    PRIMARY KEY (shrr_id),
    shrr_id integer    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    shift   smallint   NOT NULL,   -- смена
            CONSTRAINT shift_range
            CHECK(shift BETWEEN 1 AND 2),
    route   varchar(3) NOT NULL,   -- маршрут
    round   smallint   NULL,       -- выход
            CONSTRAINT round_range
            CHECK(round BETWEEN 0 AND 99),
            UNIQUE (shift, route, round)
);

-- -----------------------------------------------------
-- Table `planned_tasks_for_revenue` - плановые задания по выручке
-- -----------------------------------------------------
DROP TABLE IF EXISTS planned_tasks_for_revenue CASCADE;

CREATE TABLE IF NOT EXISTS planned_tasks_for_revenue (
    PRIMARY KEY (ptfr_date, shrr_id),
    ptfr_date     date         NOT NULL, -- дата изменений плана, мес/год
    shrr_id       integer      NOT NULL,
                  FOREIGN KEY (shrr_id) REFERENCES shift_route_round (shrr_id),
    plan_weekday  decimal(5,2) NULL,     -- план будни
    plan_saturday decimal(5,2) NULL,     -- план сб
    plan_sunday   decimal(5,2) NULL,     -- план вс
    modified_plan decimal(5,2) NULL      -- изменённый план
);

-- -----------------------------------------------------
-- Table `weekday_weekend` - справочная дней недели
-- -----------------------------------------------------
DROP TABLE IF EXISTS weekday_weekend CASCADE;

CREATE TABLE IF NOT EXISTS weekday_weekend (
    PRIMARY KEY (week_id),
    week_id  smallint   NOT NULL,
    work_day varchar(8) NOT NULL
);

-- -----------------------------------------------------
-- Table `planned_schedule` - графики рейсов
-- -----------------------------------------------------
DROP TABLE IF EXISTS planned_schedule CASCADE;

CREATE TABLE IF NOT EXISTS planned_schedule (
    PRIMARY KEY (psch_id),
    psch_id              integer    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    shrr_id              integer    NOT NULL,
                         FOREIGN KEY (shrr_id) REFERENCES  shift_route_round(shrr_id),
    week_id              smallint   NOT NULL,
                         FOREIGN KEY (week_id) REFERENCES  weekday_weekend(week_id),
                         UNIQUE (shrr_id, week_id), -- CONSTRAINT uq_psch 
    start_of_time        time       NOT NULL, -- время начала - план
    end_of_time          time       NOT NULL, -- время конец - план
    time_duration        time       NOT NULL, -- время итого - план
    second_start_of_time time       NULL,     -- время начала - II пик
    second_end_of_time   time       NULL,     -- время конец - II пик
    second_time_duration time       NULL,     -- время итого - II пик
    number_of_flights    varchar(4) NOT NULL  -- количество рейсов - план
);

-- -----------------------------------------------------
-- Table `bus_brand` - справочная МАЗов
-- -----------------------------------------------------
DROP TABLE IF EXISTS bus_brand CASCADE;

CREATE TABLE IF NOT EXISTS bus_brand (
    PRIMARY KEY (bus_id),
    bus_id        smallint   NOT NULL,
    long_or_short varchar(8) NOT NULL
);

-- -----------------------------------------------------
-- Table `calendar` - секционирование дат
-- -----------------------------------------------------
/*
CREATE TABLE calendar (
    PRIMARY KEY (logdate),
    logdate date    NOT NULL,
    wd_date date    NOT NULL,
    t_date  date    NOT NULL,
    r_date  date    NOT NULL
) PARTITION BY RANGE (logdate);
*/

-- -----------------------------------------------------
-- Table `working_date` - дата и всё что с ней связано
-- -----------------------------------------------------
DROP TABLE IF EXISTS working_date CASCADE;

CREATE TABLE IF NOT EXISTS working_date (
    PRIMARY KEY (wd_date, shrr_id, waybill),
    wd_date           date               NOT NULL,
    shrr_id           integer            NOT NULL,
                      FOREIGN KEY (shrr_id) REFERENCES  shift_route_round(shrr_id),
    proceeds          decimal(5,2)       NOT NULL, -- выручка
    number_of_flights varchar(4)         NOT NULL, -- количество рейсов - выполнено
    waybill           integer            NOT NULL,
                      CONSTRAINT waybill_value
                      CHECK(waybill > 0),
    bus_id            smallint DEFAULT 1 NOT NULL,
                      FOREIGN KEY (bus_id) REFERENCES  bus_brand(bus_id),
    start_of_time     time               NOT NULL, -- время начала - факт
    end_of_time       time               NOT NULL, -- время конец - факт
    time_duration     time               NOT NULL, -- время итого - факт
    personal_day_off  smallint           NULL,     -- если рабочий день в личный выходной, ставим '1'
    holiday           smallint           NULL,     -- перенос рабочего дня на выходной и обратно,
                                                   -- см. `weekday_weekend`
    note              text               NULL
);

-- -----------------------------------------------------
-- Table `flight` - включённые маршруты
-- -----------------------------------------------------
DROP TABLE IF EXISTS flight CASCADE;

CREATE TABLE IF NOT EXISTS flight (
    PRIMARY KEY (flight_id),
    flight_id         integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    psch_id           integer      NOT NULL,
                      FOREIGN KEY (psch_id) REFERENCES  planned_schedule(psch_id),
    flight            varchar(3)   NOT NULL, -- включённые маршруты
    plan              decimal(5,2) NOT NULL, -- план по маршрутам
    number_of_flights varchar(4)   NOT NULL, -- количество рейсов - план
    f_date            date         NOT NULL  -- дата изменений плана, мес/год
);

-- -----------------------------------------------------
-- Table `ticket` - проездные
-- -----------------------------------------------------
DROP TABLE IF EXISTS ticket CASCADE;

CREATE TABLE IF NOT EXISTS ticket (
    PRIMARY KEY (t_date),
    t_date         date    NOT NULL, 
    decade_only_b  integer NULL,
    decade_b_and_t integer NULL,
    month_only_b   integer NULL,
    month_b_and_t  integer NULL
);

-- -----------------------------------------------------
-- Table `reserve` - резерв
-- -----------------------------------------------------
DROP TABLE IF EXISTS reserve CASCADE;

CREATE TABLE IF NOT EXISTS reserve (
    PRIMARY KEY (r_date),
    r_date        date NOT NULL,
    start_of_time time NOT NULL,
    end_of_time   time NOT NULL,
    note          text NULL
);

-- -----------------------------------------------------
-- Table `sick_leave` - больничный
-- -----------------------------------------------------
DROP TABLE IF EXISTS sick_leave CASCADE;

CREATE TABLE IF NOT EXISTS sick_leave (
    PRIMARY KEY (sl_id),
    sl_id         smallint NOT NULL,
    start_of_date date     NOT NULL,
    end_of_date   date     NOT NULL,
    note          text     NULL
);

-- -----------------------------------------------------
-- Table `weekday_weekend` - вставляем данные:
-- -----------------------------------------------------

INSERT INTO weekday_weekend
VALUES (1,'weekday'),
       (2,'weekend'),
       (6,'saturday'),
       (7,'sunday');

-- -----------------------------------------------------
-- Table `bus_brand` - вставляем данные:
-- -----------------------------------------------------

INSERT INTO bus_brand
VALUES (1,'105, 215'),
       (2,'107, 103');
    